### PR TITLE
Changed Makeroid To Kodular (Contributing.md)

### PR DESCRIPTION
**Pull request by ni5arga**
In #17 Readme.md was updated. Not the contributing one. I have updated it to Makeroid To Kodular.

Please do merge this.

### CODE REVIEW

**Comment by Nisarga-Developer** [comment]
@Sander0542 @Vishwas-Adiga Thank u for merging this. I have successfully contributed here. Can I get a kodular contributor badge at the community?

Can I add bn_in language, I have already sent a pull request in the repo.???

**Comment by Vishwas-Adiga** [comment]
Feel free to work on adding Bengali translations.
However, changing Makeroid to Kodular won't get you a contributor badge. Your contributions will have to be more significant than that

**Comment by Nisarga-Developer** [comment]
Okay @Vishwas-Adiga

**Comment by Nisarga-Developer** [comment]
how to become member of kodular community on GH @Vishwas-Adiga ?

**Comment by Nisarga-Developer** [comment]
@Vishwas-Adiga 

Should I continue translating on my forked repo?
I have prepared the folder.
2 more persons are also interested in translating to bengali.
Help.

Please merge my folder here @Sander0542

**Comment by Sander0542** [comment]
You don't need to tag us in every comment. Which folder do you mean?

**Comment by Nisarga-Developer** [comment]
@Sander0542 
[](https://github.com/Nisarga-Developer/BlocklyMessages/tree/master/bn_in)

**Comment by Nisarga-Developer** [comment]
> @Sander0542
> [] (https://github.com/Nisarga-Developer/BlocklyMessages/tree/master/bn_in)

@Vishwas-Adiga

**Comment by Vishwas-Adiga** [comment]
Please don't tag us in every comment. I'll close this PR and any others you open if you continue tagging us

**Comment by Nisarga-Developer** [comment]
Alright. Can this folder be merged?

**Comment by Vishwas-Adiga** [comment]
No, the translations aren't there yet. And please open a new issue (or refer to an existing issue) for this discussion

**Comment by Nisarga-Developer** [comment]
#24 #18  I was told to stop mentioning or my PRs will be closed

**Comment by Vishwas-Adiga** [comment]
You tried to impersonate me in the Telegram group. Your account won't be reactivated. This is the end of that discussion

**Comment by Nisarga-Developer** [comment]
I impersonated you @Vishwas-Adiga ?

**Comment by Nisarga-Developer** [comment]
I DIDN'T EVER IMPERSONATED U. @Vishwas-Adiga

**Comment by cyberdevelopercoding** [comment]
> #24 #18 I was told to stop mentioning or my PRs will be closed
😂😂
1. You are suspended in the community. What is your profit doing this? @Nisarga-Developer

**Comment by cyberdevelopercoding** [comment]
> No, the translations aren't there yet. And please open a new issue (or refer to an existing issue) for this discussion

You restricted him from writing comments here, why?

**Pull request merged**
