### PR TITLE
Hi, Added Bengali Language

### PR DESCRIPTION
**Pull request by ni5arga**
Many kodular users from India (West Bengal) & Bangladesh talk in bengali language.
I have added bengali language

### CODE REVIEW

**Comment by Nisarga-Developer** [comment]
Can it be included @Vishwas-Adiga @conorshipp ??

**Comment by sagnikchatterjee450** [comment]
This translation is incorrect as you have not changed a single line in messages.js in Bengali language
Try to write the block messages in Bengali
Also add this language to translate.kodular.io

They are English only

**Comment by Nisarga-Developer** [comment]
Hey, i was just getting started. Please wait. Folder is prepared @sagnikchatterjee450

**Comment by Nisarga-Developer** [comment]
@barreeeiroo  Can It Be Enabled In The Repo Like I Said ?

**Comment by Nisarga-Developer** [comment]
Which PR To Be Specific?

**Pull request closed without merging**
