### PR TITLE
TR Translations

### PR DESCRIPTION
**Pull request by ardacebi**
This PR includes Turkish translations for the Blocks Editor.

Don't merge it until it gets completed by me. I'll tell you when it gets completed.

Opening this now for us to preview all changes by commits.

### CODE REVIEW

**Review by ardacebi — COMMENTED** [review]
Also includes enhancements to README.md and CONTRIBUTING.md

**Comment by conorshipp** [comment]
Is this finished @TurboProgramming?

**Comment by TurboProgramming** [comment]
You can merge this after 2 days. It will be done by then.

**Comment by ardacebi** [comment]
@conorshipp You can merge it for now. I'll apply any changes after the reborn.

**Comment by conorshipp** [comment]
I'll wait for @barreeeiroo to review the changes to the README first. I'm not sure we need the contributing instructions there as well.

**Comment by barreeeiroo** [comment]
@TurboProgramming Is this finished?

**Comment by ardacebi** [comment]
@barreeeiroo Yes. Partially. You can merge it for now, I'll improve it later on with another PR.

**Comment by ardacebi** [comment]
@barreeeiroo For the next update, these translations are enough as the basic stuff. I'll complete them later.

**Pull request merged**
