### PR TITLE
Italian Translation

### PR DESCRIPTION
**Pull request by barreeeiroo**
I've created this PR just to keep track of Italian translation

### CODE REVIEW

**Comment by barreeeiroo** [comment]
Tell me when it's finished 👍

**Comment by maicol07** [comment]
Translation completed!

**Comment by maicol07** [comment]
Also, I've noticed it now, please delete the other files from the Pull Request to not replace existing translations...

**Comment by barreeeiroo** [comment]
I'm going to close this PR and commit it manually as you have deleted some files that were used

**Pull request closed without merging**
